// 用户2026-10-01批准的十个主栏目；securityDomain对应官方领域名称。
export const CATEGORIES = [{"key":"diplomacy-politics","label":"外交","section":"外交情报","securityDomain":"政治安全","guide":"政局、选举、外交关系、战略联盟、制裁与国际合作竞争格局"},{"key":"conflict-arms","label":"军事","section":"军事情报","securityDomain":"军事安全","guide":"武装冲突、战争升级、军备、军演、军事部署、军控与战略稳定"},{"key":"borders-maritime","label":"地缘政治","section":"地缘政治情报","securityDomain":"国土安全","guide":"边境、领土争议、主权、海疆、领空、海洋权益与重要航道"},{"key":"supply-chain","label":"供应链","section":"供应链情报","securityDomain":"经济安全","guide":"国际贸易、关税、产业迁移、供应依赖、港口物流与经济制裁"},{"key":"finance","label":"金融","section":"金融情报","securityDomain":"金融安全","guide":"央行、主权债务、银行系统、金融制裁、跨境支付与系统性风险"},{"key":"critical-technology","label":"科技","section":"科技情报","securityDomain":"科技安全","guide":"半导体、人工智能、量子、通信、卫星、核技术与关键技术竞争及合作"},{"key":"cyber-security","label":"网络攻击","section":"网络攻击情报","securityDomain":"网络安全","guide":"网络攻击、漏洞、勒索软件、关键基础设施、数据与跨境数字风险"},{"key":"energy-minerals","label":"能源矿产","section":"能源矿产情报","securityDomain":"资源安全","guide":"稀土、关键矿产、石油、天然气、能源设施、战略储备与供应中断"},{"key":"civil-unrest","label":"社会动荡","section":"社会动荡情报","securityDomain":"社会安全","guide":"抗议、罢工、骚乱、恐袭、移民难民及影响社会稳定的重大公共事件"},{"key":"overseas-interests","label":"使领馆与海外人员","section":"使领馆与海外人员情报","securityDomain":"海外利益安全","guide":"使领馆、领事保护、海外人员与资产、投资、撤侨及国际会议参会举办"}] as const;
export const ITEM_TYPES = ["policy_change", "supply_disruption", "strategic_cooperation", "research_report", "industry_event", "opinion_analysis", "tutorial_explainer"] as const;
export const CATEGORY_TAGS = ["外交","军事","地缘政治","供应链","金融","科技","网络攻击","能源矿产","社会动荡","使领馆与海外人员"] as const;
export const TOPIC_TAGS = ["国家安全","地缘政治","国际合作","国际竞争","社会动荡","制裁","出口管制","关税","战略储备","航运","关键基础设施","央行政策","主权债务","跨境支付","关键矿产","生产中断","政策变化","研究报告","风险分析","半导体","人工智能","量子技术","先进计算","通信技术","卫星导航","太空安全","无人系统","机器人","高超声速","导弹防御","电子战","遥感情报","网络攻击","数据安全","核安全","核能","生物安全","公共卫生","生态安全","粮食安全","水资源","天然气","电网","新能源","海洋安全","极地安全","深海安全","产业竞争","移民难民","反恐","情报机构","军控","使领馆","领事保护","国际会议","国际论坛","国际峰会","会议举办","参会动态","联合声明","联合国","北约","东盟","非洲联盟","上合组织","金砖国家","G7","G20","WTO","OPEC","IEA","IMF","世界银行","IAEA","WHO","世界经济论坛","欧安组织","稀土","石油","供应链","金融"] as const;
export const ENTITY_TAGS = ["OPEC", "IEA", "IMF", "世界银行", "美联储", "欧洲央行", "OFAC", "USTR", "商务部", "USGS", "BHP", "Rio Tinto", "Glencore", "Lynas", "MP Materials", "Saudi Aramco", "ExxonMobil", "Maersk"] as const;
export const TAG_SYNONYMS: Readonly<Record<string,string>> = {"rare earths":"稀土","关键金属":"关键矿产","原油":"石油","油气":"石油","供应链安全":"供应链","金融市场":"金融","政策/监管":"政策变化","出口限制":"出口管制","贸易税":"关税","外交与政局":"外交","冲突与军备":"军事","边界与海疆":"地缘政治","贸易与供应链":"供应链","金融系统":"金融","关键科技":"科技","能源与矿产":"能源矿产","使领馆与海外人员及资产":"使领馆与海外人员"};
export const CATEGORY_BY_ITEM_TYPE: Readonly<Record<string,string>> = {policy_change:"供应链",supply_disruption:"供应链",strategic_cooperation:"外交",research_report:"科技",industry_event:"供应链",opinion_analysis:"外交",tutorial_explainer:"科技"};
export const ENTITIES: Record<string,{name:string;displayTag:string|null;aliases:string[]}> = {"opec": {"name": "OPEC", "displayTag": "OPEC", "aliases": ["OPEC", "欧佩克"]}, "iea": {"name": "IEA", "displayTag": "IEA", "aliases": ["IEA", "国际能源署"]}, "imf": {"name": "IMF", "displayTag": "IMF", "aliases": ["IMF", "国际货币基金组织"]}, "world-bank": {"name": "世界银行", "displayTag": "世界银行", "aliases": ["World Bank", "世界银行"]}, "fed": {"name": "美联储", "displayTag": "美联储", "aliases": ["Federal Reserve", "美联储"]}, "ecb": {"name": "欧洲央行", "displayTag": "欧洲央行", "aliases": ["European Central Bank", "欧洲央行"]}, "ofac": {"name": "OFAC", "displayTag": "OFAC", "aliases": ["OFAC", "美国财政部外国资产控制办公室"]}, "ustr": {"name": "USTR", "displayTag": "USTR", "aliases": ["USTR", "美国贸易代表办公室"]}, "mofcom": {"name": "商务部", "displayTag": "商务部", "aliases": ["MOFCOM", "商务部"]}, "usgs": {"name": "USGS", "displayTag": "USGS", "aliases": ["USGS", "美国地质调查局"]}, "bhp": {"name": "BHP", "displayTag": "BHP", "aliases": ["BHP", "必和必拓"]}, "rio-tinto": {"name": "Rio Tinto", "displayTag": "Rio Tinto", "aliases": ["Rio Tinto", "力拓"]}, "glencore": {"name": "Glencore", "displayTag": "Glencore", "aliases": ["Glencore", "嘉能可"]}, "lynas": {"name": "Lynas", "displayTag": "Lynas", "aliases": ["Lynas", "莱纳斯"]}, "mp-materials": {"name": "MP Materials", "displayTag": "MP Materials", "aliases": ["MP Materials"]}, "aramco": {"name": "Saudi Aramco", "displayTag": "Saudi Aramco", "aliases": ["Saudi Aramco", "沙特阿美"]}, "exxonmobil": {"name": "ExxonMobil", "displayTag": "ExxonMobil", "aliases": ["ExxonMobil", "埃克森美孚"]}, "maersk": {"name": "Maersk", "displayTag": "Maersk", "aliases": ["Maersk", "马士基"]}};
export const IDENTITY_LEXICON: ReadonlyArray<{id:string;name:string;patterns:RegExp[]}> = Object.entries(ENTITIES).map(([id,e]) => ({id,name:e.name,patterns:e.aliases.map(a=>new RegExp(a.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),"i"))}));
export const PUBLISHER_DOMAINS: ReadonlyArray<{entityId:string;domains:readonly string[]}> = [{entityId:"opec",domains:["opec.org"]},{entityId:"iea",domains:["iea.org"]},{entityId:"fed",domains:["federalreserve.gov"]},{entityId:"ecb",domains:["ecb.europa.eu"]},{entityId:"ofac",domains:["ofac.treasury.gov"]},{entityId:"mofcom",domains:["mofcom.gov.cn"]}];
export const IDENTITY_CONTEXT_ALIASES: ReadonlyArray<{entityId:string;pattern:RegExp}> = [];
